### ISSUE TITLE
Make the station connections a ternary relationship.

### ISSUE THREAD

**Issue by Nightwing52** [DartExplore/dart-explore-backend#37]
For the sake of simplicity I would like to make the station-station-color relation a ternary relationship as opposed to breaking it across two entities. This may not be as normalized but greatly simplifies both the table script and Java code. My main reasoning is the Java code will be much more accessible.

**Comment by Nightwing52** [comment]
Looking at various options and might implement this as a Map on the Java side. I just can't get my head around the Embedded way.

**Comment by Nightwing52** [comment]
This will be closed by branch [repositoryInitialDesign](https://github.com/DartExplore/dart-explore-backend/tree/repositoryInitialDesign) when merged.

**Comment by Nightwing52** [comment]
I am sure to forget my reasoning by tomorrow morning so I will explain why the Map made more sense to me in this particular context: basically, in the business logic the station connection relation is always being used in an iterative fashion. What I mean is that to find out how to go from point A to B you check all of As' neighbors, then the neighbors' neighbors', etc. We aren't using it so much as a data store as we are making it a graph.

**Comment by ZaneBartlett1** [comment]
I feel like I understand how you'd generate it using a map, I was just going to use a SQL query for this. If you're trying to do it through the ORM it might be hard, but I already had a query for this lol. It's fine and we can do this, but I would have liked a bit more discussion since we I brought it up you said however I want to implement it.

We can talk to make sure I understand how you're wanting to do this though and I'm not missing anything
