### ISSUE TITLE
Implement repository layer tests

### ISSUE THREAD

**Issue by Nightwing52** [DartExplore/dart-explore-backend#38]
Now that we are finalizing the initial DB design and mapping we should spend some time testing to make sure common queries like getting all stations on a given line, all POIs at a given station, etc. are working. Let's use our meeting next week to discuss this.

**Comment by ZaneBartlett1** [comment]
Currently your test data doesn't meet the database table constraints so some of it's being failed to populate, which will definitely affect queries

**Comment by Nightwing52** [comment]
Everything inserts properly in MySQL so you will need to resolve #40 before we tackle this issue.

**Comment by ZaneBartlett1** [comment]
I changed the dockerfile to use MySQL, so I am using the same database as you are, currently. I actually don't think the MySQL image will automatically run the init.sql (well I'm sure it would somehow, just not how I have it set up right now) so I have to manually run the init.sql in a console. 

How is it not failing for you? In this line - https://github.com/DartExplore/dart-explore-backend/blob/1f74b7f3c0ca1c65ccc3424c3e60035d17a40661/src/main/resources/init.sql#L45, there's a constraint check, and then three lines down you make insert statements that do not meet that constraint. You're not getting an error running that?

**Comment by Nightwing52** [comment]
I am not sure how it didn't get committed but that constraint should be removed. Basically, the colors are few and never changing but this is not the case with amenities.

**Comment by ZaneBartlett1** [comment]
When you made this issue, were you referring to queries through the database or through a repository? I was playing around in Postgres and it seems like most things are valid. I've done 
* all stations for a given color
* all Points of Interest at a given station
* all amenities at a given POI

I haven't been super stringent, but since we have #51 I think we'll figure out any issues there, so it seems kind of redundant to have both of these issues up past basic queries to validate that relationships are set up correctly at the database level. I'm going to close this issue out for now, but feel free to reopen and let me know if there's anything we need to do here that wouldn't be covered in #51 and I'll get that covered!

**Comment by Nightwing52** [comment]
I am reopening because yes this needs to be done on the repository level not the DB level. The service level needs to call these methods in the repository layer. You will translate your queries to the JPQL query language which is pretty straightforward. Details here. It is possible to do a native query but I recommend against this.

https://www.baeldung.com/spring-data-jpa-query

**Comment by ZaneBartlett1** [comment]
So what is being added here as an issue that won't be addressed in #51?

**Comment by Nightwing52** [comment]
We need to write tests in JUnit to ensure the functions added by #51 work properly.

**Comment by ZaneBartlett1** [comment]
Changed name after discussion in Signal

**Comment by Nightwing52** [comment]
I have been trying to work on some unit tests today but seem to be running into config issues. Might do Postman testing until we get this resolved.

**Comment by ZaneBartlett1** [comment]
See mention above for more information
