### ISSUE TITLE
Update dockerfile and init.sql to be postgress instead of MySQL

### ISSUE THREAD

**Issue by ZaneBartlett1** [DartExplore/dart-explore-backend#40]
Currently we're using a MySQL database but want to move over to a Postgress database

**Comment by Nightwing52** [comment]
I agree. I would like to have two setups. You should look it up but in Spring you can have profiles (dev, prod, etc.) which maybe gets read as an environment variable. So we will keep the script and properties file for MySQL and have a separate one for Postgres.

**Comment by Nightwing52** [comment]
Issue #32 is now closed so you now have an example of how to use environment variables. This is also helpful if you ever need to use them in code.

https://www.baeldung.com/spring-boot-properties-env-variables

**Comment by ZaneBartlett1** [comment]
I agree that it's worth talking about having those different environments. I would like to keep the environments as much the same as possible where there's not a lot of overhead though, and having the databases be the same type seems straightforward in this context. 
You can run into a lot of hard to figure out problems if your dev environment doesn't match your production environment. A more extreme example would be like if we use H2 for our development environment. That's obviously not good because it's just such a different database that we can't be sure that if something is working with it, it'll work on production database. The same type of thing is true with MySQL and Postgress though. So if our production database is going to end up being postgress, our development database should be. 

Unless there's a reason not to, I would really like to make sure we're all using the same environment, and I would like that environment to use Postgress. When I compared the two, Postgress is a lot more user friendly (aka, won't blow your foot off) and the main reasons we would use MySQL don't seem to apply here. Let me know your thoughts on any of that.

**Comment by Nightwing52** [comment]
I chose MySQL for my temporary environment because MySQL is very simple and easy to setup and is what I am comfortable with. Completely agree that Postgres in general is the superior database (for most definitions of superior) but most of this data will be fairly static in production (think of the stations and their connections) and so much of the database is just serving as a datastore. A lot of data validation will go on in the Java side as well and will be fairly easy to determine if any bad data has been input.

**Comment by Nightwing52** [comment]
We discussed this over Signal but will just put it here again for records. 

Since we now put much of the setup in environment variables all that is left is to make a copy of the table script but for Postgres which was already needed to begin with and no extra work for you. This will I will work on getting Docker setup on my end. Let's keep both table scripts though.

**Comment by ZaneBartlett1** [comment]
So I need to do more testing to figure out what's happening, but I'm running into an issue running the init.sql against the postgres database after updating the syntax to it. 

I appears that [here](https://github.com/DartExplore/dart-explore-backend/blob/b8dbeea5e5ad13b35add9933158ad8ff672d9b0a/src/main/resources/init.sql#L89), we're creating and we're making amenity key as one of the foreign keys, however the amenity key is a composite of the id and amenity itself. This means that on the poi_amenity table, it's expecting the amenity_id and amenity.

I'm tired and so I forget what we agreed to and why, but at this current time (which I will think about more tomorrow) I'm thinking the best thing to do is drop having the Amenity table having a composite key since it has an id. The making the poi_amenity just be the poi_id and amenity_id. Then I need to go to the class and update it to reflect this schema change.

Like mentioned, I'll be thinking about this more tomorrow, but if you could mention why making the amenity key [a composite](https://github.com/DartExplore/dart-explore-backend/blob/main/src/main/resources/init.sql#L43) and/or if the above does sound good, then I can start to get further on this.
